CREATE TABLE COURSE(
   course_ID INT PRIMARY KEY,
   course_Name VARCHAR(50),
   CREDITS NUMERIC (2),
   Department _ID NUMERIC (3)
  );
  DESE COURSE;
  
  INSERT INTO COURSE VALUES(101,'Database',4,10);
  INSERT INTO COURSE VALUES (102,'java',3,10);
  INSERT INTO COURSE VALUES (103,'python',4,30);
  SELECT*FROM COURSE;
